var impfpass = {
        Diphtherie : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 10,
            letzteImpfung: [,],
            termin: "",
        },
        FSME : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 5,
            letzteImpfung: [,],
            termin: "",
        },
        Grippe : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 1,
            letzteImpfung: [,],
            termin: "",
        },
        HepatitisB : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        Hib : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        HPV : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        Keuchhusten : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        Masern : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        Meningokokken : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        Mumps : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        //TODO ab 60 alle 6 Jahre, ab 60 als ausstehend
        Pneumokokken : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        //TODO ab 9. Lebensjahr 1 mal
        Polio : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        Rotaviren : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        Roeteln : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        Tetanus : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 10,
            letzteImpfung: [,],
            termin: "",
        },
        Windpocken : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        //TODO ab 60 1 mal
        Guertelrose : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        Covid19 : {
            datum: [],
            charge: [],
            impfstoff: [],
            arzt: [],
            intervall: 0,
            letzteImpfung: [,],
            termin: "",
        },
        
        
}